<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "about_translate".
 *
 * @property integer $id
 * @property string $short_description
 * @property string $description
 * @property integer $about_id
 * @property string $url
 * @property string $meta_title
 * @property string $meta_description
 * @property string $meta_keywords
 *
 * @property \common\models\About $about
 * @property string $aliasModel
 */
abstract class AboutTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'about_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['about_id' , 'lang_id'], 'required'],
            [['description'], 'string'],
            [['about_id' , 'lang_id'], 'integer'],
            [['meta_description', 'meta_keywords'], 'string', 'max' => 255],
            [['about_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\About::className(), 'targetAttribute' => ['about_id' => 'id']],
            [['lang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Lang::className(), 'targetAttribute' => ['lang_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'short_description' => 'Short Description',
            'description' => 'Description',
            'about_id' => 'About ID',
            'url' => 'Url',
            'meta_title' => 'Meta Title',
            'meta_description' => 'Meta Description',
            'meta_keywords' => 'Meta Keywords',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAbout()
    {
        return $this->hasOne(\common\models\About::className(), ['id' => 'about_id']);
    }




}
