<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "banner_page_position".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $sort
 * @property integer $page_id
 * @property integer $position_id
 * @property integer $banner_id
 *
 * @property \common\models\Banners $banner
 * @property \common\models\Page $page
 * @property \common\models\Position $position
 * @property string $aliasModel
 */
abstract class BannerPagePosition extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banner_page_position';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'page_id', 'position_id', 'banner_id'], 'required'],
            [['status', 'sort', 'page_id', 'position_id', 'banner_id'], 'integer'],
            [['banner_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Banners::className(), 'targetAttribute' => ['banner_id' => 'id']],
            [['page_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Page::className(), 'targetAttribute' => ['page_id' => 'id']],
            [['position_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Position::className(), 'targetAttribute' => ['position_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'sort' => 'Sort',
            'page_id' => 'Page',
            'position_id' => 'Position',
            'banner_id' => 'Banner',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBanner()
    {
        return $this->hasOne(\common\models\Banners::className(), ['id' => 'banner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPage()
    {
        return $this->hasOne(\common\models\Page::className(), ['id' => 'page_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosition()
    {
        return $this->hasOne(\common\models\Position::className(), ['id' => 'position_id']);
    }




}
