<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "banner_translate".
 *
 * @property integer $id
 * @property string $title
 * @property integer $lang_id
 * @property integer $banner_id
 *
 * @property \common\models\Banners $banner
 * @property \common\models\Lang $lang
 * @property string $aliasModel
 */
abstract class BannersTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banner_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['lang_id', 'banner_id'], 'required'],
            [['lang_id', 'banner_id'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['banner_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Banners::className(), 'targetAttribute' => ['banner_id' => 'id']],
            [['lang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Lang::className(), 'targetAttribute' => ['lang_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'lang_id' => 'Lang ID',
            'banner_id' => 'Banner ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBanner()
    {
        return $this->hasOne(\common\models\Banners::className(), ['id' => 'banner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(\common\models\Lang::className(), ['id' => 'lang_id']);
    }




}
