<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "blog_gallery".
 *
 * @property integer $id
 * @property integer $status
 * @property string $image
 * @property integer $blog_id
 *
 * @property \common\models\Blog $blog
 * @property string $aliasModel
 */
abstract class BlogGallery extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog_gallery';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'blog_id'], 'required'],
            [['status', 'blog_id'], 'integer'],
            [['image'], 'string', 'max' => 255],
            [['blog_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Blog::className(), 'targetAttribute' => ['blog_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'image' => 'Image',
            'blog_id' => 'Blog ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBlog()
    {
        return $this->hasOne(\common\models\Blog::className(), ['id' => 'blog_id']);
    }




}
