<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\SluggableBehavior;

/**
 * This is the base-model class for table "carousel_translate".
 *
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property integer $lang_id
 * @property integer $carousel_id
 *
 * @property \common\models\Carousel $carousel
 * @property \common\models\Lang $lang
 * @property string $aliasModel
 */
abstract class CarouselTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carousel_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['lang_id', 'carousel_id'], 'required'],
            [['lang_id', 'carousel_id'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['carousel_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Carousel::className(), 'targetAttribute' => ['carousel_id' => 'id']],
            [['lang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Lang::className(), 'targetAttribute' => ['lang_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'lang_id' => 'Lang ID',
            'carousel_id' => 'Carousel ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarousel()
    {
        return $this->hasOne(\common\models\Carousel::className(), ['id' => 'carousel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(\common\models\Lang::className(), ['id' => 'lang_id']);
    }




}
