<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\CategoryTranslate;
use common\models\Lang;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "category".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $sort
 * @property string $icon
 * @property string $created_at
 *
 * @property \common\models\CategoryTranslate[] $categoryTranslates
 * @property \common\models\SubCategory[] $subCategories
 * @property string $aliasModel
 */
abstract class Category extends \yii\db\ActiveRecord
{

    public $title;
    public $meta_keywords;

    public  $rasm;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status'], 'required'],
            [['status', 'sort'], 'integer'],
            [['icon'], 'string', 'max' => 255],

            ['title' , 'each' , 'rule' => ['string']],
            ['title' , 'required'],
            ['rasm' , 'image' , 'extensions' => 'jpg , png , jpeg' , 'maxWidth' => 100 , 'maxHeight' => 100 ,'message' => "rasm o'lchami ko'pi bilan 100x100 bo'lishi kerak." , 'maxSize' => 512000, 'tooBig' => 'Limit is 500KB'],
            ['meta_keywords' , 'each' , 'rule' => ['string']],
            ['meta_keywords' , 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'sort' => 'Sort',
            'created_at' => 'Created At',
            'icon' => 'Icon',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryTranslates()
    {
        return $this->hasMany(\common\models\CategoryTranslate::className(), ['category_id' => 'id']);
    }

    public function getCategoryTranslate(){
        return $this->hasOne(CategoryTranslate::className() , ['category_id' => 'id'])->andWhere(['lang_id' => \Yii::$app->languageId->id]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubCategories()
    {
        return $this->hasMany(\common\models\SubCategory::className(), ['category_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        if($this->rasm){
            if(file_exists(\Yii::getAlias('@uploads').'/category/'.$this->icon)){
                if($this->icon != null){

                    unlink(\Yii::getAlias('@uploads').'/category/'.$this->icon);
                }
            }
            $filename = floor(microtime(true)*10000).'.'.$this->rasm->extension;
            $this->icon = $filename;
            if($this->icon){
                $this->rasm->saveAs(\Yii::getAlias('@uploads').'/category/'.$this->icon);
            }
        }


        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $category = \common\models\Category::findOne($this->id);
        
        if($category && Yii::$app->controller->action->id == 'create'){
            foreach(Lang::find()->all() as $lang){

                $translate = new CategoryTranslate([
                    'title' => $this->title[$lang->url],
                    'url' => toAscii($this->title[$lang->url]),
                    'meta_title' => $this->title[$lang->url],
                    'meta_keywords' => $this->meta_keywords[$lang->url],
                    'lang_id' => $lang->id,
                    'category_id' => $this->id
                ]);

                $translate->save();
            }

            
        }elseif($category && \Yii::$app->controller->action->id = 'update'){
            
            foreach(Lang::find()->all() as $language){
                $translate = CategoryTranslate::find()->where(['category_id' => $category->id])->andWhere(['lang_id' => $language->id])->one();
                if($translate){

                    $translate->title = $this->title[$language->url];
                    $translate->url = toAscii($this->title[$language->url]);
                    $translate->meta_title = $this->title[$language->url];
                    $translate->meta_keywords = $this->meta_keywords[$language->url];
                    $translate->save();
                }else{
                    $newTranslate = new CategoryTranslate([
                        'title' => $this->title[$language->url],
                        'url' => toAscii($this->title[$language->url]),
                        'meta_title' => $this->title[$language->url],
                        'meta_keywords' => $this->meta_keywords[$language->url],
                        'lang_id' => $language->id,
                        'category_id' => $this->id
                        ]);
                    $newTranslate->save();
                }
            }
        }
        return parent::afterSave($insert , $changedAttributes);
    }

}
