<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "company_gallery".
 *
 * @property integer $id
 * @property integer $status
 * @property string $image
 * @property integer $company_id
 *
 * @property \common\models\Company $company
 * @property string $aliasModel
 */
abstract class CompanyGallery extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company_gallery';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'company_id'], 'required'],
            [['status', 'company_id'], 'integer'],
            [['image'], 'string', 'max' => 255],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'image' => 'Image',
            'company_id' => 'Company',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'company_id']);
    }




}
