<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_gallery".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $product_id
 * @property string $image
 *
 * @property \common\models\Product $product
 * @property string $aliasModel
 */
abstract class ProductGallery extends \yii\db\ActiveRecord
{


    public $files;
    public $file;

    public $productId;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_gallery';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'product_id'], 'required'],
            [['status', 'product_id'], 'integer'],
            ['productId' , 'integer'],
            [['image'], 'string', 'max' => 255],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Product::className(), 'targetAttribute' => ['product_id' => 'id']],

            [['files'] , 'file' , 'extensions' => 'gif , png , jpg , jpeg' , 'maxSize' => 1024*1024*1 , 'tooBig' => 'Limit is 1 MB' , 'maxFiles' => 4],
            [['file'] , 'file' , 'extensions' => 'gif , png , jpg , jpeg' , 'maxSize' => 1024*1024*1 , 'tooBig' => 'Limit is 1 MB']

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'product_id' => 'Product ',
            'image' => 'Image',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\common\models\Product::className(), ['id' => 'product_id']);
    }




}
