<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\Lang;
use common\models\ProductTranslate;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\imagine\Image;
use Imagine\Gd;
use Imagine\Image\Box;
use Imagine\Image\BoxInterface;
/**
 * This is the base-model class for table "product".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $sort
 * @property string $image
 * @property string $price
 * @property integer $visit
 * @property integer $sub_category_id
 * @property integer $company_id
 * @property string $created_at
 *
 * @property \common\models\Carousel[] $carousels
 * @property \common\models\Company $company
 * @property \common\models\SubCategory $subCategory
 * @property \common\models\ProductGallery[] $productGalleries
 * @property \common\models\ProductTranslate[] $productTranslates
 * @property string $aliasModel
 */
abstract class Product extends \yii\db\ActiveRecord
{

    public $title;
    public $short_description;
    public $description;
    public $meta_title;
    public $meta_description;
    public $meta_keywords;
    public $rasm;
    const TYPE_BEST = 10;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'sub_category_id', 'company_id'], 'required'],
            [['status', 'sort', 'visit', 'sub_category_id', 'company_id' , 'type'], 'integer'],
            [['image', 'price'], 'string', 'max' => 255],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['sub_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SubCategory::className(), 'targetAttribute' => ['sub_category_id' => 'id']],

            ['title' , 'each' , 'rule' => ['string']],
            ['title' , 'required'],

            [['meta_description'] , 'each' , 'rule' => ['string']],
            // [['meta_description'] , 'required'],

            [['short_description'] , 'each' , 'rule' => ['string']],
            [['short_description'] , 'required'],

            ['description' , 'each' , 'rule' => ['string']],
            ['description' , 'required'],


            ['rasm' , 'file' , 'extensions' => ['png' , 'jpg' , 'jpeg'] , 'maxSize' => 1024*1024, 'tooBig' => 'Limit is 1MB'],
            ['meta_keywords' , 'each' , 'rule' => ['string']],
            ['meta_keywords' , 'required']

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'sort' => 'Sort',
            'image' => 'Image',
            'price' => 'Price',
            'created_at' => 'Created At',
            'visit' => 'Visit',
            'sub_category_id' => 'Sub Category',
            'company_id' => 'Company',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarousels()
    {
        return $this->hasMany(\common\models\Carousel::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubCategory()
    {
        return $this->hasOne(\common\models\SubCategory::className(), ['id' => 'sub_category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductGalleries()
    {
        return $this->hasMany(\common\models\ProductGallery::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductTranslates()
    {
        return $this->hasMany(\common\models\ProductTranslate::className(), ['product_id' => 'id']);
    }

    public function getProductTranslate()
    {
        return $this->hasOne(\common\models\ProductTranslate::className(), ['product_id' => 'id'])->andWhere(['lang_id' => \Yii::$app->languageId->id]);
    }


    public function beforeSave($insert)
    {
        
        if($this->rasm){
            if(file_exists(\Yii::getAlias('@uploads').'/product/'.$this->image)){
                if($this->image != null){

                    unlink(\Yii::getAlias('@uploads').'/product/'.$this->image);

                    if(file_exists(\Yii::getAlias('@uploads').'/product/thumb/'.$this->image))
                    unlink(\Yii::getAlias('@uploads').'/product/thumb/'.$this->image);
                }
            }
            $filename = floor(microtime(true)*10000).'.'.$this->rasm->extension;
            $this->image = $filename;
            if($this->image){
                $this->rasm->saveAs(\Yii::getAlias('@uploads').'/product/'.$this->image);

                Image::thumbnail(\Yii::getAlias('@uploads').'/product/'.$this->image, 250, 230)
                ->save(\Yii::getAlias('@uploads').'/product/thumb/'.$this->image, ['quality' => 100]);
            }
        }


        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $product = \common\models\Product::findOne($this->id);
        
        if($product && \Yii::$app->controller->action->id == 'create'){
            foreach(Lang::find()->all() as $lang){

                $translate = new ProductTranslate([
                    'title' => $this->title[$lang->url],
                    'meta_description' => $this->short_description[$lang->url],
                    'short_description' => $this->short_description[$lang->url],
                    'description' => $this->description[$lang->url],
                    'url' => toAscii($this->title[$lang->url]),
                    'meta_title' => $this->title[$lang->url],
                    'meta_keywords' => $this->meta_keywords[$lang->url],
                    'lang_id' => $lang->id,
                    'product_id' => $product->id
                ]);

                $translate->save();
            }

            
        }elseif($product && \Yii::$app->controller->action->id = 'update'){
            
            foreach(Lang::find()->all() as $language){
                $translate = ProductTranslate::find()->where(['product_id' => $product->id])->andWhere(['lang_id' => $language->id])->one();
                if($translate){

                    $translate->title = $this->title[$language->url];
                    $translate->meta_description = $this->short_description[$language->url];
                    $translate->short_description = $this->short_description[$language->url];
                    $translate->description = $this->description[$language->url];
                    $translate->url = toAscii($this->title[$language->url]);
                    $translate->meta_title = $this->title[$language->url];
                    $translate->meta_keywords = $this->meta_keywords[$language->url];
                    $translate->save();
                }else{
                    $newTranslate = new ProductTranslate([
                        'title' => $this->title[$language->url],
                        'meta_description' => $this->short_description[$language->url],
                        'short_description' => $this->short_description[$language->url],
                        'description' => $this->description[$language->url],
                        'url' => toAscii($this->title[$language->url]),
                        'meta_title' => $this->title[$language->url],
                        'meta_keywords' => $this->meta_keywords[$language->url],
                        'lang_id' => $language->id,
                        'product_id' => $product->id
                        ]);
                    $newTranslate->save();
                }
            }
        }
        return parent::afterSave($insert , $changedAttributes);
    }

}
