<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\Lang;
use common\models\ServiceTranslate;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\imagine\Image;

/**
 * This is the base-model class for table "service".
 *
 * @property integer $id
 * @property string $email
 * @property integer $status
 * @property integer $sort
 * @property string $image
 * @property string $created_at
 *
 * @property \common\models\ServiceTranslate[] $serviceTranslates
 * @property string $aliasModel
 */
abstract class Service extends \yii\db\ActiveRecord
{

    public $title;
    public $short_description;
    public $description;
    public $meta_title;
    public $meta_description;
    public $meta_keywords;
    public $rasm;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status' , 'phone'], 'required'],
            [['status', 'sort'], 'integer'],
            [['email', 'image' , 'phone' , 'website'], 'string', 'max' => 255],
            [['email'], 'unique'],

            ['title' , 'each' , 'rule' => ['string']],
            ['title' , 'required'],

            [['meta_description'] , 'each' , 'rule' => ['string']],
            [['meta_description'] , 'required'],

            [['short_description'] , 'each' , 'rule' => ['string']],
            [['short_description'] , 'required'],

            ['description' , 'each' , 'rule' => ['string']],
            ['description' , 'required'],


            ['rasm' , 'image' , 'extensions' => 'jpg , png , jpeg' ,'maxWidth' => 500 , 'maxSize' => 1024*1024, 'tooBig' => 'Limit is 1MB'],
            ['meta_keywords' , 'each' , 'rule' => ['string']],
            ['meta_keywords' , 'required']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'status' => 'Status',
            'sort' => 'Sort',
            'image' => 'Image',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceTranslates()
    {
        return $this->hasMany(\common\models\ServiceTranslate::className(), ['service_id' => 'id']);
    }
    public function getServiceTranslate()
    {
        return $this->hasOne(\common\models\ServiceTranslate::className(), ['service_id' => 'id'])->andWhere(['lang_id' => \Yii::$app->languageId->id]);
    }


    public function beforeSave($insert)
    {
        
        if($this->rasm){
            if(file_exists(\Yii::getAlias('@uploads').'/service/'.$this->image)){
                if($this->image != null){

                    unlink(\Yii::getAlias('@uploads').'/service/'.$this->image);

                    if(file_exists(\Yii::getAlias('@uploads').'/service/thumb/'.$this->image))
                    unlink(\Yii::getAlias('@uploads').'/service/thumb/'.$this->image);
                }
            }
            $filename = floor(microtime(true)*10000).'.'.$this->rasm->extension;
            $this->image = $filename;
            if($this->image){
                $this->rasm->saveAs(\Yii::getAlias('@uploads').'/service/'.$this->image);

                Image::thumbnail(\Yii::getAlias('@uploads').'/service/'.$this->image, 250, 200)
                ->save(\Yii::getAlias('@uploads').'/service/thumb/'.$this->image, ['quality' => 100]);
            }
        }


        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $service = \common\models\Service::findOne($this->id);
        
        if($service && \Yii::$app->controller->action->id == 'create'){
            foreach(Lang::find()->all() as $lang){

                $translate = new ServiceTranslate([
                    'title' => $this->title[$lang->url],
                    'meta_description' => $this->short_description[$lang->url],
                    'short_description' => $this->short_description[$lang->url],
                    'description' => $this->description[$lang->url],
                    'url' => toAscii($this->title[$lang->url]),
                    'meta_title' => $this->title[$lang->url],
                    'meta_keywords' => $this->meta_keywords[$lang->url],
                    'lang_id' => $lang->id,
                    'service_id' => $service->id
                ]);

                $translate->save();
            }

            
        }elseif($service && \Yii::$app->controller->action->id = 'update'){
            
            foreach(Lang::find()->all() as $language){
                $translate = ServiceTranslate::find()->where(['service_id' => $service->id])->andWhere(['lang_id' => $language->id])->one();
                if($translate){

                    $translate->title = $this->title[$language->url];
                    $translate->meta_description = $this->short_description[$language->url];
                    $translate->short_description = $this->short_description[$language->url];
                    $translate->description = $this->description[$language->url];
                    $translate->url = toAscii($this->title[$language->url]);
                    $translate->meta_title = $this->title[$language->url];
                    $translate->meta_keywords = $this->meta_keywords[$language->url];
                    $translate->save();
                }else{
                    $newTranslate = new ServiceTranslate([
                        'title' => $this->title[$language->url],
                        'meta_description' => $this->short_description[$language->url],
                        'short_description' => $this->short_description[$language->url],
                        'description' => $this->description[$language->url],
                        'url' => toAscii($this->title[$language->url]),
                        'meta_title' => $this->title[$language->url],
                        'meta_keywords' => $this->meta_keywords[$language->url],
                        'lang_id' => $language->id,
                        'service_id' => $service->id
                        ]);
                    $newTranslate->save();
                }
            }
        }
        return parent::afterSave($insert , $changedAttributes);
    }

}
