<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\SluggableBehavior;

/**
 * This is the base-model class for table "service_translate".
 *
 * @property integer $id
 * @property string $title
 * @property string $short_description
 * @property string $description
 * @property integer $lang_id
 * @property integer $service_id
 * @property string $url
 * @property string $meta_title
 * @property string $meta_description
 * @property string $meta_keywords
 *
 * @property \common\models\Lang $lang
 * @property \common\models\Service $service
 * @property string $aliasModel
 */
abstract class ServiceTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_translate';
    }

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'url',
                'slugAttribute' => 'url',
                'ensureUnique'=>true,
            ]
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'short_description', 'lang_id', 'service_id'], 'required'],
            [['short_description'], 'string'],
            [['lang_id', 'service_id'], 'integer'],
            [['title', 'description', 'url', 'meta_title', 'meta_description', 'meta_keywords'], 'string', 'max' => 255],
            [['url'], 'unique'],
            [['lang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Lang::className(), 'targetAttribute' => ['lang_id' => 'id']],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Service::className(), 'targetAttribute' => ['service_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'short_description' => 'Short Description',
            'description' => 'Description',
            'lang_id' => 'Lang ID',
            'service_id' => 'Service ID',
            'url' => 'Url',
            'meta_title' => 'Meta Title',
            'meta_description' => 'Meta Description',
            'meta_keywords' => 'Meta Keywords',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(\common\models\Lang::className(), ['id' => 'lang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(\common\models\Service::className(), ['id' => 'service_id']);
    }




}
