<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\SluggableBehavior;

/**
 * This is the base-model class for table "sub_category_translate".
 *
 * @property integer $id
 * @property string $title
 * @property integer $lang_id
 * @property integer $sub_category_id
 * @property string $url
 * @property string $meta_title
 * @property string $meta_description
 * @property string $meta_keywords
 *
 * @property \common\models\Lang $lang
 * @property \common\models\SubCategory $subCategory
 * @property string $aliasModel
 */
abstract class SubCategoryTranslate extends \yii\db\ActiveRecord
{

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'url',
                'slugAttribute' => 'url',
                'ensureUnique'=>true,
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sub_category_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'lang_id', 'sub_category_id'], 'required'],
            [['lang_id', 'sub_category_id'], 'integer'],
            [['title', 'url', 'meta_title', 'meta_description', 'meta_keywords'], 'string', 'max' => 255],
            [['url'], 'unique'],
            [['lang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Lang::className(), 'targetAttribute' => ['lang_id' => 'id']],
            [['sub_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SubCategory::className(), 'targetAttribute' => ['sub_category_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'lang_id' => 'Lang ID',
            'sub_category_id' => 'Sub Category ID',
            'url' => 'Url',
            'meta_title' => 'Meta Title',
            'meta_description' => 'Meta Description',
            'meta_keywords' => 'Meta Keywords',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(\common\models\Lang::className(), ['id' => 'lang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubCategory()
    {
        return $this->hasOne(\common\models\SubCategory::className(), ['id' => 'sub_category_id']);
    }




}
