<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "auth_assignment".
 *
 * @property string $item_name
 * @property integer $user_id
 * @property integer $created_at
 *
 * @property \app\modules\crud\models\AuthItem $itemName
 * @property string $aliasModel
 */
abstract class AuthAssignment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'auth_assignment';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['item_name', 'user_id'], 'required'],
            [['user_id'], 'integer'],
            [['item_name'], 'string', 'max' => 64],
            [['item_name'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\AuthItem::className(), 'targetAttribute' => ['item_name' => 'name']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'item_name' => Yii::t('models', 'Item Name'),
            'user_id' => Yii::t('models', 'User ID'),
            'created_at' => Yii::t('models', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemName()
    {
        return $this->hasOne(\app\modules\crud\models\AuthItem::className(), ['name' => 'item_name']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\AuthAssignmentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\AuthAssignmentQuery(get_called_class());
    }


}
